export { useSettings } from "./useSettings";
export { SettingRow } from "./SettingRow";
export { GeneralTab } from "./GeneralTab";
export { AppearanceTab } from "./AppearanceTab";
export { NotchTab } from "./NotchTab";
export { CalendarSyncPage } from "./CalendarSyncPage";
export { DockTab } from "./DockTab";
export { OverlaysTab } from "./OverlaysTab";
export { ProcessesTab } from "./ProcessesTab";
export { AboutTab } from "./AboutTab";
export type { WidgetConfig, SettingsTab, SettingRowProps } from "./types";
